 [env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200

; Flash 大小 (2MB for ESP32-C3 Mini)
board_build.flash_size = 2MB

; 添加组件头文件路径
build_flags =
    -Isrc
    -Isrc/wifi
    -Isrc/web
    -Isrc/ble

; 使用自定义组件目录
board_build.components_dirs =
    components

; 自定义分区表
board_build.partitions = partitions.csv

; 确保上传时复位
upload_speed = 921600
